import { useState } from 'react'
import Modal from '../components/Modal'
import { saveAsset } from '../lib/api'
import { money } from '../lib/utils'
const blank = { code:'', old_code:'', name:'', category:'', status:'Available', condition:'Good', location:'Yard', serial:'', replacement_value:'', notes:'' }
export default function Assets({ data, refresh }) {
  const [editing,setEditing]=useState(null),[search,setSearch]=useState(''),[saving,setSaving]=useState(false)
  const assets=data.assets.filter(a=>(`${a.code} ${a.name} ${a.category}`).toLowerCase().includes(search.toLowerCase()))
  const submit=async()=>{if(!editing.code||!editing.name||!editing.category)return alert('Code, name and category are required.');setSaving(true);try{await saveAsset(editing);setEditing(null);await refresh()}catch(e){alert(e.message)}finally{setSaving(false)}}
  return <section className="panel"><div className="panel-heading"><div><h2>Assets</h2><p>{data.assets.length} assets in the shared register.</p></div><div className="inline-actions"><input placeholder="Search assets" value={search} onChange={e=>setSearch(e.target.value)}/><button className="primary" onClick={()=>setEditing({...blank})}>New asset</button></div></div>
  <div className="table-wrap"><table><thead><tr><th>Code</th><th>Asset</th><th>Category</th><th>Status</th><th>Condition</th><th>Location</th><th>Value</th></tr></thead><tbody>{assets.map(a=><tr key={a.id} onClick={()=>setEditing({...a})}><td><strong>{a.code}</strong></td><td>{a.name}</td><td>{a.category}</td><td><span className={`badge ${a.status.toLowerCase().replace(' ','-')}`}>{a.status}</span></td><td>{a.condition}</td><td>{a.location||'—'}</td><td>{money(a.replacement_value)}</td></tr>)}</tbody></table></div>
  {editing&&<Modal title={editing.id?editing.code:'New asset'} onClose={()=>setEditing(null)} actions={<><button onClick={()=>setEditing(null)}>Cancel</button><button className="primary" disabled={saving} onClick={submit}>Save asset</button></>}><div className="form-grid">{[['Code','code'],['Old code','old_code'],['Name','name'],['Category','category'],['Location','location'],['Serial','serial']].map(([l,k])=><label key={k}>{l}<input value={editing[k]||''} onChange={e=>setEditing({...editing,[k]:e.target.value})}/></label>)}<label>Status<select value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value})}>{['Available','On Hire','In Repair','Lost','Retired'].map(v=><option key={v}>{v}</option>)}</select></label><label>Condition<select value={editing.condition} onChange={e=>setEditing({...editing,condition:e.target.value})}>{['Good','Damaged','In Repair','Lost','Retired'].map(v=><option key={v}>{v}</option>)}</select></label><label>Replacement value<input type="number" value={editing.replacement_value??''} onChange={e=>setEditing({...editing,replacement_value:e.target.value})}/></label><label className="full">Notes<textarea value={editing.notes||''} onChange={e=>setEditing({...editing,notes:e.target.value})}/></label></div><div className="qr-preview"><img alt="QR code" src={`https://api.qrserver.com/v1/create-qr-code/?size=160x160&data=${encodeURIComponent(`${location.origin}/?asset=${editing.id||editing.code}`)}`}/><span>QR label for {editing.code||'new asset'}</span></div></Modal>}
  </section>
}
